name: "datawise-build-bun"
description: "datawise build bun"
inputs:
  DATAWISE_PACKAGES_TOKEN:
    required: false
    default: "invalid"

runs:
  using: "composite"
  steps:
    - name: Export DATAWISE_PACKAGES_TOKEN as env var
      shell: bash
      run: |
        echo "DATAWISE_PACKAGES_TOKEN=${{ inputs.DATAWISE_PACKAGES_TOKEN }}" >> $GITHUB_ENV
  
    - name: Restore Bun install cache
      uses: actions/cache@v4
      with:
        path: ./.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
#   you should have this for private repository in bunfig.toml
#   [install.scopes]
#   "@datawise-ai" = { token = "$DATAWISE_PACKAGES_TOKEN", url = "https://npm.pkg.github.com" }

    - name: update bunfig.tml [bun install cache] 
      shell: bash
      run: |
        echo '[install.cache]'                >> bunfig.toml
        echo 'dir = "./.bun/install/cache"'   >> bunfig.toml   # the directory to use for the cache
        echo 'disableManifest = false'        >> bunfig.toml   # when true, always resolve the latest versions from the registry

    - name: cat bunfig.tml  
      shell: bash
      run: |
        cat bunfig.toml 
    
    - name: Show bunfig.toml
      shell: bash
      run: cat bunfig.toml

    - name: Remove .npmrc (if exists)
      shell: bash
      run: rm -f .npmrc

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Bun install
      shell: bash
      run: bun install --frozen-lockfile

    - name: Bun Lint
      shell: bash
      run: bun run lint

    - name: Bun NEXT build
      shell: bash
      run: bun run build
